### ISSUE TITLE
Link to Chapter 1 is broken

### ISSUE THREAD

**Issue by frank9843** [Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups#13]
In the general readme.md of this sample, in step 2, the link to "Chapter 1" leads to a 404.
I found chapter 1 here: https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/tree/master/chapter1

The current link pointing to chapter one is: https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/blob/master/Chapter1/README.md

**Comment by derisen** [comment]
@frank9843 good catch, thanks! Will address this in the current PR
