### ISSUE TITLE
Chapter 1 TodoListSPA source code fails to build

### ISSUE THREAD

**Issue by mrob1600** [Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups#15]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [ ] "@azure/msal-angular": "^2.0.0-alpha.0"

## Description
These lines throw an error:
this.authService.loginPopup({...this.msalGuardConfig.authRequest})
 this.authService.loginRedirect({...this.msalGuardConfig.authRequest});

## Error Message
error TS2345: Argument of type '{ prompt?: string | undefined; state?: string | undefined; authority?: string | undefined; correlationId?: string | undefined; claims?: string | undefined; resourceRequestMethod?: string | undefined; ... 10 more ...; scopes?: string[] | undefined; } | { ...; }' is not assignable to parameter of type 'PopupRequest | undefined'.
  Type '{ prompt?: string | undefined; state?: string | undefined; authority?: string | undefined; correlationId?: string | undefined; claims?: string | undefined; resourceRequestMethod?: string | undefined; ... 10 more ...; scopes?: string[] | undefined; }' is not assignable to type 'PopupRequest'.
    Type '{ prompt?: string | undefined; state?: string | undefined; authority?: string | undefined; correlationId?: string | undefined; claims?: string | undefined; resourceRequestMethod?: string | undefined; ... 10 more ...; scopes?: string[] | undefined; }' is not assignable to type '{ scopes: string[]; }'.
      Types of property 'scopes' are incompatible.
        Type 'string[] | undefined' is not assignable to type 'string[]'.
          Type 'undefined' is not assignable to type 'string[]'.

## Security

- [ ] Is this issue security related?

## Regression

- [ ] Did this behavior work before?

Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Download TodoListSPA
npm install
ng build --prod

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
The source code would build successfully

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by markrullo** [comment]
I'm seeing the exact same issue.

**Comment by derisen** [comment]
@mrob1600, @markrullo 's solution is correct. Modify `app.component.ts` in TodoListSPA as such:

```typescript
  login() {
    if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
      if (this.msalGuardConfig.authRequest){
        this.authService.loginPopup({...this.msalGuardConfig.authRequest} as PopupRequest)
          .subscribe(() => this.checkAccount());
        } else {
          this.authService.loginPopup()
            .subscribe(() => this.checkAccount());
      }
    } else {
      if (this.msalGuardConfig.authRequest){
        this.authService.loginRedirect({...this.msalGuardConfig.authRequest} as RedirectRequest);
      } else {
        this.authService.loginRedirect();
      }
    }
  }
```

We have made the changes in the [current PR](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/pull/14).

**Comment by mrob1600** [comment]
Excellent. Thanks!
