### ISSUE TITLE
Is a client_secret needed to run the SPA example and where to get it?

### ISSUE THREAD

**Issue by andrantis** [Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups#17]
## Library

- [ ] `@azure/msal-angular@2.0.0-alpha.3`
- [ ] `@azure/msal-browser@2.9.0`

## Description

I been following the instruction to run the example from chapter 1. But I keep getting error below when trying to login. It seem that I'm missing a setting for the `client_secret`, where would I get that and where does it need to be entered? I only see the setting in the appsettings.json in the API.

```json
claims: "{"access_token":{"capolids":{"essential":true,"values":["29ab2b01-4103-4857-b082-bbd11047e33b"]}}}"
correlation_id: "af402f90-a33d-42aa-a1de-ecdf57ddd62c"
error: "invalid_client"
error_codes: [7000218]
0: 7000218
error_description: "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
↵Trace ID: 718bbd59-3d47-480c-820b-8be8fc8c9400
↵Correlation ID: af402f90-a33d-42aa-a1de-ecdf57ddd62c
↵Timestamp: 2021-03-26 19:07:05Z"
error_uri: "https://login.microsoftonline.com/error?code=7000218"
timestamp: "2021-03-26 19:07:05Z"
trace_id: "718bbd59-3d47-480c-820b-8be8fc8c9400"
```

**Comment by derisen** [comment]
@andrantis Angular SPA project should not need a client secret. Can you double check your Azure AD app registration (TodoListSPA)? Go to the **Authentication** blade and make sure you added the platform as "Single-page application" (not "Web").

**Comment by andrantis** [comment]
That was the issue. Thanks for the quick reply.
