### ISSUE TITLE
Slight documentation tweak - TaskUser vs TaskUsers 

### ISSUE THREAD

**Issue by markrullo** [Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups#4]
Hello,
I think there is an error in the Chapter1 sample ReadMe.md .  It states to add this to the manifest

```
      {
         "allowedMemberTypes": [
            "User"
         ],
         "description": "Users can read and modify their TodoList but cannot see others' lists",
         "displayName": "TaskUsers",
         "id": "a816142a-2e8e-46c4-9997-f984faccb625",
         "isEnabled": true,
         "lang": null,
         "origin": "Application",
         "value": "TaskUsers"
      }
```
In the code it checks for the singular TaskUser where the role added is the plural TaskUsers.  Once I changed the manifest to the singular, things worked out.  I'd make the change in the readme.md, but I've never made an open source contribution before.  I'm not exactly sure how to do it correctly.

**Comment by derisen** [comment]
@markrullo thank you so much for catching this. You're more than welcome to make a PR. You can edit the readme directly, just hit the pen icon:

![screenshot](https://user-images.githubusercontent.com/13197548/90179837-ee229a00-dd62-11ea-8df9-0c8a6134184d.png)

**Comment by markrullo** [comment]
@derisen, thanks for walking me through this.  I just submitted a pull request as my first open source contribution!  Do I close the issue once it's been accepted?

**Comment by derisen** [comment]
awesome! I'll link the PR; when merged, the issue will be closed.
